accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
      url(r'^signup/$',views.signup_view,name="signup"),
      url(r'^login/$',views.login_view,name="login"),
      url(r'^logout/$',views.logout_view,name="logout"),
    ]

djangoWrapper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url


from pages.views import home_view, contact_view, about_view

urlpatterns = [
    #path('accounts/', accounts_view),
    path('',home_view, name='home'), 
    path('contact/',contact_view),
    path('about/',about_view),
    path('admin/', admin.site.urls),
    url('accounts/',include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
	title = models.CharField(max_length=50)
	description = models.TextField(null=True,blank=True)
	price = models.DecimalField(decimal_places=2,max_digits=10)
	summary =  models.TextField(default="Django is cool")

class User(models.Model):
	name = models.TextField()
	isAutorized =  models.BooleanField()
	email =  models.EmailField(max_length=250)
	alternate_email = models.EmailField(max_length=250)	

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm #use the native Django form
from django.contrib.auth import login, logout

# Create your views here.

#handle signup request
def signup_view(request):
  if request.method=='POST': #Handle POST request
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save() #save to database
      #log the user in
      login(request,user)
      return redirect('accounts:signup')
  else:
    form = UserCreationForm()
  return render(request,'accounts/signup.html',{'form':form})

#Handle login request
def login_view(request):
  if request.method=='POST': #Handle POST request
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
      #login the user
      user = form.get_user()
      login(request,user)
      return redirect('accounts:signup')
  else:
    form = AuthenticationForm()    
  return render(request,'accounts/login.html',{'form':form})

#Handle logout request
def logout_view(request):
  if request.method=='POST': #Handle POST request
    logout(request)
    return redirect('accounts:signup')

pages/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def home_view(request,*args,**kwargs):
	print(request.user)
	#return HttpResponse("<h1>Welcome to the wrapper!</h1>")
	return render(request,"home.html",{})

def contact_view(*args,**kwargs):
  return HttpResponse("<h1>Wanna contact me?</h1>")

def about_view(request,*args,**kwargs):
  print(request.user)
	#my_context = { 
  #    "my_clg":"BPHC",
  #    "my_degrees":["eco","ece"] 
  #}
  return HttpResponse("<h1>Welcome to non-working About!</h1>")
  #return render(request,"about.html",my_context) 

users/views.py
from django.shortcuts import render

# Create your views here.

templates/about.html
{% extends 'base.html' %}

{% block content %}
        <h1>About me??</h1>
	<p>
		I'm from {{ my_clg }}. Need I say more? 
	</p>
	<ul>
		<li></li>
		<li></li>
<ul>
{% for my-sub_item in my_degree %}
	<li>{{ my_sub_item }} </li>	 
{% endfor %}
</ul>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>LogIn</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login">
  </form>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>SignUp</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SignUp">
  </form>
{% endblock %}

templates/base.html
<!doctype html>
<html>
<head><title>Email Service</title></head>
<body>
  <nav>
    <ul>
      <li>
        <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
          {% csrf_token %}
          <button type="submit">Logout</button>
        </form>
      </li>
    </ul>
  </nav>
{% block content %}
	replace me 
{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
	<h1>{{ request.user}}, welcome to the wrapper</h1>
{% endblock %}